project:
  type: website
  output-dir: _site

website:
  title: "Andrea Vaiano"
  description: "Academic website"
  navbar:
    left:
      - href: index.qmd
        text: Bio
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - text: Talks & Teaching
        menu:
          - href: talks/teaching.qmd
            text: Teaching (TA)
          - href: talks/seminars.qmd
            text: Seminars
          - href: talks/conferences.qmd
            text: Conferences
      - href: cv.qmd
        text: CV
      # - href: noice/index.qmd
      #   text: Noice - my blog
    right:
      - icon: envelope
        href: "mailto:andrea.vaiano@uniroma1.it"

format:
  html:
    theme: editorial.scss
    css: styles.css
    toc: false
    page-layout: full
